#!/usr/bin/env python3
"""Generate the `CODESS_*` variable reference from the source that defines it.

A table of variables maintained by hand is wrong by the next change, and this
one carries four facts per row -- reader, default, flag, validation -- each of
which lives in a different module. Reading them rather than restating them is
what makes the document re-derivable.

    python tools/variable_reference.py            # write contrib/perf/ZeroVars.md
    python tools/variable_reference.py --check    # fail if it would change
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from codess.settings import SETTINGS  # noqa: E402

TARGET = REPO / "contrib" / "perf" / "ZeroVars.md"

# How each bound treats 0, read from its consumer rather than assumed. A bound
# whose consumer guards with `if bound and ...` is disabled by 0; one that
# compares directly is not, and 0 is its strictest possible value.
ZERO_MEANING = {
    "CODESS_MAX_SCAN_DIRECTORIES": ">= 0, disabled by 0",
    "CODESS_SCAN_TIMEOUT": ">= 0, disabled by 0",
    "CODESS_KEEP_SNAPSHOTS": ">= 0, disabled by 0",
    "CODESS_QUERY_BYTE_LIMIT": "> 0",
    "CODESS_SOURCE_READ_MAX": "> 0",
    "CODESS_MAX_CODESS_DB_BYTES": "> 0",
    "CODESS_MAX_CURSOR_DB_BYTES": "> 0",
    "CODESS_DAYS": "0 to 3650",
    "CODESS_MIN_SIZE": ">= 0",
    "CODESS_STORE_ROOT": 'absolute; rejects `.`, `..`, `""`',
    "CODESS_CC_PROJECTS": "absolute",
    "CODESS_CODEX_SESSIONS": "absolute",
    "CODESS_CODEX_ARCHIVED_SESSIONS": "absolute",
    "CODESS_CURSOR_DATA": "absolute",
    "CODESS_RAW_MODE": "one of the declared modes",
    "CODESS_AGGREGATORS": "relative to the work root",
    "CODESS_EXCLUDE_REVIEW_DIRS": "relative to the work root",
    "CODESS_MAX_TRANSCRIPT_BYTES": "> 0",
    "CODESS_MAX_CURSOR_CONTAINER_BYTES": "> 0",
    "CODESS_MAX_EVENTS_PER_SOURCE": "> 0",
    "CODESS_MAX_EVENTS_PER_SESSION": "> 0",
    "CODESS_MAX_CONTEXT_CONTENT_CHARS": "> 0",
}


def env_table_rows() -> list[tuple[str, str, str]]:
    """The `(variable, reader, default)` triples, parsed rather than matched.

    `ast` rather than a regular expression: a default is an arbitrary
    expression -- `GB(2)`, `str(Path.home() / ".codess")` -- and a regex that
    stops at the first `)` truncates exactly the interesting ones.
    """
    tree = ast.parse((REPO / "src" / "codess" / "config.py").read_text(encoding="utf-8"))
    for node in ast.walk(tree):
        if not (isinstance(node, ast.Assign) and node.targets):
            continue
        target = node.targets[0]
        if not (isinstance(target, ast.Name) and target.id == "_IS_ENV_TABLE"):
            continue
        rows = []
        for element in getattr(node.value, "elts", []):
            parts = getattr(element, "elts", [])
            if len(parts) != 3:
                continue
            name, reader, default = parts
            if not (isinstance(name, ast.Constant) and isinstance(reader, ast.Name)):
                continue
            rows.append((
                str(name.value),
                reader.id.removeprefix("env_"),
                ast.unparse(default),
            ))
        return sorted(rows)
    return []


def render() -> str:
    by_variable = {setting.variable: setting for setting in SETTINGS}
    lines = [
        "# ZeroVars",
        "",
        "Every `CODESS_*` variable, how it is read, what sets it, and what bounds",
        "it. Generated by `tools/variable_reference.py`; run that rather than",
        "editing, and `--check` fails when the source has moved ahead of it.",
        "",
        "## Resolution",
        "",
        "**Flag, then variable, then built-in default**, each narrower than the",
        "last: a flag names one invocation, a variable one shell, a default every",
        "machine that never chose. `settings.resolve` applies it for a caller",
        "holding an `argparse.Namespace`; `settings.resolve_named` for one holding",
        "the value directly, which is what a leaf module that cannot import",
        "`config` uses.",
        "",
        "**A boolean composes rather than overrides.** `--force` with",
        "`CODESS_FORCE=0` is force, and so is `CODESS_FORCE=1` with no flag: a",
        "`store_true` flag cannot express *off*, so treating its absence as an",
        "override would make the variable unsettable from any shell that also",
        "passes flags.",
        "",
        "## Bounds",
        "",
        "**0 does not mean the same thing to every bound**, so each row states its",
        "own. `disabled by 0` marks a bound whose consumer guards with",
        "`if bound and ...`; `> 0` marks one whose consumer compares directly,",
        "where 0 is the strictest possible value rather than none --",
        "`SOURCE_READ_MAX` of 0 reads nothing, a `byte_limit` of 0 emits no rows.",
        "",
        "## Variables",
        "",
        "| Variable | Reader | Default | Flag | Bound |",
        "|---|---|---|---|---|",
    ]
    for variable, reader, default in env_table_rows():
        setting = by_variable.get(variable)
        flag = setting.flag if setting and setting.flag else "--"
        bound = ZERO_MEANING.get(variable, "--" if reader == "bool" else "none")
        lines.append(
            f"| `{variable}` | `{reader}` | `{default}` | `{flag}` | {bound} |"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="report whether the file is current instead of writing it",
    )
    args = parser.parse_args(argv)
    body = render()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current == body:
            print(f"{TARGET.relative_to(REPO)} is current")
            return 0
        print(f"{TARGET.relative_to(REPO)} is stale; run without --check")
        return 1
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(body, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
